import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NativeHistoryIntentMarker from './components/NativeHistoryIntentMarker';
import SiteHeader from './components/SiteHeader';
import SiteFooter from './components/SiteFooter';
import { AuthProvider } from '@/lib/auth/client';
import { getCurrentUserResult } from '@/lib/auth/server';
import { MessagingRealtimeProvider } from '@/lib/messagingRealtime';
import { countCurrentUserUnreadConversations } from '@/lib/supabase/messagingServer';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authResult = await getCurrentUserResult();
  const unreadCountResult =
    authResult.status === 'authenticated'
      ? await countCurrentUserUnreadConversations()
      : null;
  const initialUnreadConversationCount =
    unreadCountResult?.ok ? unreadCountResult.count : 0;

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AuthProvider>
          <MessagingRealtimeProvider
            initialUnreadConversationCount={initialUnreadConversationCount}
          >
            <NativeHistoryIntentMarker />
            <SiteHeader initialAuthStatus={authResult.status} />
            {children}
            <SiteFooter />
          </MessagingRealtimeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
